"""movie tabl

Revision ID: df085efb9d3e
Revises: f3f2813cf259
Create Date: 2020-09-26 16:58:01.433507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df085efb9d3e'
down_revision = 'f3f2813cf259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('score', sa.String(length=64), nullable=True),
    sa.Column('director', sa.String(length=120), nullable=True),
    sa.Column('popularity', sa.String(length=64), nullable=True),
    sa.Column('genre', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_director'), 'movie', ['director'], unique=False)
    op.create_index(op.f('ix_movie_genre'), 'movie', ['genre'], unique=False)
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=True)
    op.create_index(op.f('ix_movie_popularity'), 'movie', ['popularity'], unique=False)
    op.create_index(op.f('ix_movie_score'), 'movie', ['score'], unique=False)
    op.create_index(op.f('ix_movie_timestamp'), 'movie', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_timestamp'), table_name='movie')
    op.drop_index(op.f('ix_movie_score'), table_name='movie')
    op.drop_index(op.f('ix_movie_popularity'), table_name='movie')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_index(op.f('ix_movie_genre'), table_name='movie')
    op.drop_index(op.f('ix_movie_director'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
